export const sliderItems = [
    {
      id: 1,
      img: "https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg",
      title: "COCO",
      desc: "The most hilarious and ecstatic movie.",
      bg: "f5fafd",
    },
    {
      id: 2,
      img: "https://lh3.googleusercontent.com/proxy/wKFnoZt-LOE-zgOFMlNgSSljutOQynkUFK1RFP195_mZjaLo3d7ZhlUL3dbr5W2RoWRwQls3Z0-GWVwk6C0o9b3O2ZsPKB3SzEj6ze9aYQ",
      title: "Inception",
      desc: "The Dream Is Real.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: "https://terrigen-cdn-dev.marvel.com/content/qa/1x/5ae4ca-MLou_13x19_DolbyAtAMC_Handout_v4_online_lg.jpg",
      title: "Avengers",
      desc: "Infinity War.",
      bg: "fbf0f4",
    },
    {
      id: 4,
      img: "http://www.slashfilm.com/wp/wp-content/images/2017-bestposter-thorragnarok.jpg",
      title: "Thor",
      desc: "Ragnarok",
      bg: "fbf0f4",
    },
    {
      id: 5,
      img: "https://movieposters.ie/wp-content/uploads/2013/05/RIPD-movie-poster1.jpg",
      title: "R.I.P.D",
      desc: "Rest In Pease Department",
      bg: "fbf0f4",
    },
    {
      id: 6,
      img: "https://m.media-amazon.com/images/M/MV5BMjFjMTQxZTYtYzdkZi00ZWMyLWJlN2QtY2IzYTc3MzdlZGY5XkEyXkFqcGdeQXVyNjcyNjcyMzQ@._V1_.jpg",
      title: "The Map Of Tiny Perfect Things",
      desc: "Infinity War.",
      bg: "fbf0f4",
    },
    {
      id: 7,
      img: "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/2c039bdb2f54ea0a56e16b3b721c9081866940324ef8a23a55e4cfe86f276995._RI_V_TTW_.jpg",
      title: "The curious case of benjamin button",
      desc: "BENJAMIN BUTTON",
      bg: "fbf0f4",
    },
  ];